name: APIs.io Tags
description: Browse APIs, capabilities, and more by tag across the APIs.io network.
image: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg
url: https://tags.apis.io

node: website
nav_active: tags

keywords:
  - APIs
  - Search
  - Discovery

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts"]
include: [".well-known"]

github_org: api-search
github_repo: tags
